### ISSUE TITLE
upload Version 1.0.0

### ISSUE THREAD

**Issue by VoidEUW** [VoidEUW/stacat#1]
# Todo
- [ ] Remove Debug logs
- [x] Check for memory leaks
- [ ] Verbalize all rules and graphically show them

> [!IMPORTANT]
> Needs table of contents, language support for German, English and Chinese. Explain each command in depth and show an example command for some letters.
